package dnsmasq

import (
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/joyops/infra-pxe/internal/config"
	"github.com/joyops/infra-pxe/internal/store"
)

// Manager controls the dnsmasq process.
type Manager struct {
	cfg   *config.Config
	store *store.Store
	pid   int
}


func New(cfg *config.Config, s *store.Store) *Manager {
	return &Manager{cfg: cfg, store: s}
}
// RegenerateConfig reloads dnsmasq after task changes.
// DHCP static bindings (hostsfile) are owned EXCLUSIVELY by the bindings API
// (POST/DELETE /api/dhcp/bindings, frontend DHCP page) — tasks never write
// hostsfile entries, so task create/update/delete only needs a reload.
func (m *Manager) RegenerateConfig() {
	confDir := m.cfg.DnsmasqConfDir()

	// If no DHCP config has been pushed yet, skip — dnsmasq won't start until configured via API.
	mainConf := filepath.Join(confDir, "dnsmasq.conf")
	if _, err := os.Stat(mainConf); os.IsNotExist(err) {
		slog.Info("no dnsmasq config file yet, waiting for DHCP configuration via API")
	}

	if m.IsRunning() {
		m.Reload()
	}
}


// DhcpConfigParams holds the full DHCP configuration parameters pushed via API.
type DhcpConfigParams struct {
	Interface  string `json:"interface"`
	DhcpStart  string `json:"dhcp_start"`
	DhcpEnd    string `json:"dhcp_end"`
	Netmask    string `json:"netmask"`
	Gateway    string `json:"gateway"`
	Dns        string `json:"dns"`
	LeaseTime  string `json:"lease_time"`
	EnableDns  bool   `json:"enable_dns"`
}

// WriteConfig renders and writes dnsmasq.conf from params.
// It knows local paths (tftp root, logs, pid file, hosts file) from config.
// Caller should restart/reload dnsmasq after this.
func (m *Manager) WriteConfig(p *DhcpConfigParams) string {
	confDir := m.cfg.DnsmasqConfDir()
	hostsPath := filepath.Join(confDir, "dnsmasq.hostsfile")
	tftpRoot := filepath.Join(m.cfg.BootDir(), "tftp")
	logFile := filepath.Join(confDir, "dnsmasq.log")
	pidFile := m.resolvePidPath()
	scriptPath := m.cfg.Dnsmasq.DhcpScript
	if !filepath.IsAbs(scriptPath) {
		scriptPath = filepath.Join(m.cfg.BaseDir, scriptPath)
	}
	serverAddr := m.resolveServerAddr(p.Interface)

	port := "0"
	if p.EnableDns {
		port = "53"
	}

	leasePath := filepath.Join(confDir, "dnsmasq.leases")
	leaseTime := p.LeaseTime
	if leaseTime == "" {
		leaseTime = m.cfg.Dnsmasq.LeaseTime
	}

	// Build DNS option conditionally
	dnsOption := ""
	if p.Dns != "" {
		dnsOption = fmt.Sprintf("dhcp-option=6,%s", p.Dns)
	}
	// Build gateway option conditionally (empty gateway = no default route)
	gatewayOption := ""
	if p.Gateway != "" {
		gatewayOption = fmt.Sprintf("dhcp-option=3,%s", p.Gateway)
	}

	conf := fmt.Sprintf(`# Auto-generated by infra-pxe
port=%s
interface=%s
# Run as root: dnsmasq would otherwise drop to the dnsmasq user and lose
# access to the pxe-owned boot/tftp and data/dnsmasq directories.
user=root
bind-dynamic
dhcp-hostsfile=%s
dhcp-leasefile=%s
dhcp-authoritative
dhcp-no-override
dhcp-lease-max=253
dhcp-range=%s,%s,%s,%s
%s
%s
enable-tftp
tftp-root=%s

# Architecture detection (IANA RFC 4578)
# 0=BIOS, 7=EFI BC(x86_64), 9=EFI x86-64, 11=EFI ARM64, 16=EFI HTTP Boot
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-match=set:efi-x86_64,option:client-arch,9
dhcp-match=set:efi-http,option:client-arch,16
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-match=set:bios,option:client-arch,0

# iPXE user-class detection
dhcp-userclass=set:ipxe,iPXE

# Boot file selection
dhcp-boot=tag:ipxe,http://%s/render/menu.ipxe
dhcp-boot=tag:!ipxe,tag:efi-http,http://%s/tftp/efi64/ipxe.efi
dhcp-boot=tag:!ipxe,tag:efi-x86_64,efi64/ipxe.efi
		dhcp-boot=tag:!ipxe,tag:efi-arm64,efiarm/ipxe.efi
dhcp-boot=tag:!ipxe,tag:bios,bios/undionly.kpxe

# DHCP event hook
dhcp-script=%s

log-dhcp
log-facility=%s
pid-file=%s
`, port, p.Interface, hostsPath, leasePath,
		p.DhcpStart, p.DhcpEnd, p.Netmask, leaseTime,
		gatewayOption,
		dnsOption,
		tftpRoot,
		serverAddr, serverAddr,
		scriptPath, logFile, pidFile)
	confPath := filepath.Join(confDir, "dnsmasq.conf")
	os.MkdirAll(confDir, 0o755)
	os.WriteFile(confPath, []byte(conf), 0o644)
	return conf
}

// Start launches dnsmasq. Stores PID in memory for reliable stop.
func (m *Manager) Start() error {
	if m.IsRunning() {
		return nil
	}

	// Kill any stray dnsmasq
	exec.Command("pkill", "-f", "dnsmasq").Run()
	time.Sleep(300 * time.Millisecond)

	confDir := m.cfg.DnsmasqConfDir()
	confPath := filepath.Join(confDir, "dnsmasq.conf")
	if _, err := os.Stat(confPath); os.IsNotExist(err) {
		// Try restoring from DB
		dbCfg := m.store.DB.GetDhcpConfig()
		if dbCfg.Interface != "" && dbCfg.DhcpStart != "" {
			m.WriteConfig(&DhcpConfigParams{
				Interface: dbCfg.Interface,
				DhcpStart: dbCfg.DhcpStart,
				DhcpEnd:   dbCfg.DhcpEnd,
				Netmask:   dbCfg.Netmask,
				Gateway:   dbCfg.Gateway,
				Dns:       dbCfg.Dns,
				LeaseTime: dbCfg.LeaseTime,
				EnableDns: dbCfg.EnableDns,
			})
		}
		// Still no config? Can't start — DHCP not configured yet
		if _, err := os.Stat(confPath); os.IsNotExist(err) {
			return fmt.Errorf("DHCP not configured yet (use PUT /api/dhcp/config or MCP dhcp_config_update)")
		}
	}

	cmd := exec.Command(m.cfg.Dnsmasq.Binary, "--conf-file="+confPath, "--keep-in-foreground")
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		return err
	}

	m.pid = cmd.Process.Pid
	// Reap the master when it exits; otherwise every Stop/Start cycle leaks a zombie
	// under the PXE process (Go does not auto-reap abandoned exec children).
	go cmd.Wait()
	os.WriteFile(m.resolvePidPath(), []byte(strconv.Itoa(m.pid)), 0o644)

	time.Sleep(100 * time.Millisecond)
	if syscall.Kill(m.pid, 0) != nil {
		m.pid = 0
		os.Remove(m.resolvePidPath())
		return fmt.Errorf("dnsmasq exited immediately")
	}
	return nil
}

// Stop kills dnsmasq by memory PID, PID file, then pkill.
func (m *Manager) Stop() {
	if m.pid > 0 {
		syscall.Kill(m.pid, syscall.SIGTERM)
		m.pid = 0
	}
	if pid := m.getPID(); pid > 0 {
		syscall.Kill(pid, syscall.SIGTERM)
	}
	os.Remove(m.resolvePidPath())
	exec.Command("pkill", "-f", "dnsmasq").Run()
}

// IsRunning checks if dnsmasq is alive (not zombie) via PID.
func (m *Manager) IsRunning() bool {
	if m.pid > 0 && isProcessAlive(m.pid) {
		return true
	}
	pid := m.getPID()
	return pid > 0 && isProcessAlive(pid)
}

// isProcessAlive checks if a process exists and is not a zombie.
func isProcessAlive(pid int) bool {
	if syscall.Kill(pid, 0) != nil {
		return false
	}
	// Check for zombie state via /proc
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/status", pid))
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "State:") {
			return !strings.Contains(line, "zombie") && !strings.Contains(line, "Z (")
		}
	}
	return true
}

// Reload sends SIGHUP to dnsmasq.
func (m *Manager) Reload() {
	pid := m.pid
	if pid <= 0 {
		pid = m.getPID()
	}
	if pid > 0 {
		syscall.Kill(pid, syscall.SIGHUP)
	}
}

// Status returns dnsmasq status info.
func (m *Manager) Status() map[string]any {
	running := m.IsRunning()
	hostsPath := filepath.Join(m.cfg.DnsmasqConfDir(), "dnsmasq.hostsfile")
	hostCount := 0
	if data, err := os.ReadFile(hostsPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) != "" {
				hostCount++
			}
		}
	}
	result := map[string]any{"running": running, "host_entries": hostCount}
	if running && m.pid > 0 {
		result["pid"] = m.pid
	}
	return result
}

func (m *Manager) getPID() int {
	pidPath := m.resolvePidPath()
	data, err := os.ReadFile(pidPath)
	if err != nil {
		return 0
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0
	}
	return pid
}

func (m *Manager) resolvePidPath() string {
	p := m.cfg.Dnsmasq.PidFile
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(m.cfg.BaseDir, p)
}

// resolveServerAddr determines the "ip:port" address target machines use to reach this PXE server.
// Priority: DB pxe_server_ip > interface IP from the DHCP config param.
func (m *Manager) resolveServerAddr(iface string) string {
	ip, port := m.store.GetPxeServer()
	if ip == "" || ip == "127.0.0.1" {
		// Fallback: get IP from the DHCP interface
		ip = getInterfaceIP(iface)
	}
	if ip == "" {
		ip = "127.0.0.1"
	}
	if port == "" {
		port = strconv.Itoa(m.cfg.Server.Port)
	}
	return ip + ":" + port
}

// getInterfaceIP returns the first IPv4 address of a network interface.
func getInterfaceIP(ifName string) string {
	if ifName == "" {
		return ""
	}
	iface, err := net.InterfaceByName(ifName)
	if err != nil {
		return ""
	}
	addrs, err := iface.Addrs()
	if err != nil {
		return ""
	}
	for _, addr := range addrs {
		if ipnet, ok := addr.(*net.IPNet); ok && ipnet.IP.To4() != nil {
			return ipnet.IP.String()
		}
	}
	return ""
}
